steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'

- script: |
    go version
    go get -v -t -d ./...
    if [ -f Gopkg.toml ]; then
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep status
    fi
  workingDirectory: '$(modulePath)'
  displayName: 'Check project dependencies'

- script: |
    make manager
    make clusterctl
  workingDirectory: '$(modulePath)'
  displayName: 'Build controllers manager and clusterctl'

- script: |
    set -e
    echo "Running unit tests for machine actuator"
    make machine-unit-tests
    echo "Running unit tests for cluster actuator"
    make cluster-unit-tests
  workingDirectory: '$(modulePath)'
  displayName: 'Run unit tests'
